# Generated by Django 3.1.4 on 2021-01-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_informationaboutvoting_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationaboutvoting',
            name='user_create',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
