# Generated by Django 3.1.4 on 2021-01-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_informationaboutvoting_user_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationaboutvoting',
            name='user_create',
        ),
    ]
