# Generated by Django 3.1.4 on 2021-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_informationaboutvoting_user_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationaboutvoting',
            name='user_create',
        ),
        migrations.AddField(
            model_name='votings',
            name='user_create',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
